[2025-09-15T22:34:16.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: just_orchestration.prepare_workspace manual__2025-09-15T18:04:04.797241+00:00 [queued]>
[2025-09-15T22:34:16.392+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: just_orchestration.prepare_workspace manual__2025-09-15T18:04:04.797241+00:00 [queued]>
[2025-09-15T22:34:16.393+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-15T22:34:16.552+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): prepare_workspace> on 2025-09-15 18:04:04.797241+00:00
[2025-09-15T22:34:16.566+0000] {standard_task_runner.py:60} INFO - Started process 419 to run task
[2025-09-15T22:34:16.578+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'just_orchestration', 'prepare_workspace', 'manual__2025-09-15T18:04:04.797241+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/another.py', '--cfg-path', '/tmp/tmpmj3pgjjo']
[2025-09-15T22:34:16.591+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask prepare_workspace
[2025-09-15T22:34:16.934+0000] {task_command.py:423} INFO - Running <TaskInstance: just_orchestration.prepare_workspace manual__2025-09-15T18:04:04.797241+00:00 [running]> on host 44984dd3f90c
[2025-09-15T22:34:17.351+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='williams' AIRFLOW_CTX_DAG_ID='just_orchestration' AIRFLOW_CTX_TASK_ID='prepare_workspace' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T18:04:04.797241+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-15T18:04:04.797241+00:00'
[2025-09-15T22:34:17.355+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T22:34:17.361+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    mkdir -p /opt/Models\n    mkdir -p /opt/data\n    mkdir -p /opt/metrics\n    echo "Pipeline started at $(date)" > /opt/Models/pipeline_log.txt\n    ']
[2025-09-15T22:34:17.381+0000] {subprocess.py:86} INFO - Output:
[2025-09-15T22:34:17.391+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/Models’: Permission denied
[2025-09-15T22:34:17.397+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/data’: Permission denied
[2025-09-15T22:34:17.402+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/metrics’: Permission denied
[2025-09-15T22:34:17.411+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 5: /opt/Models/pipeline_log.txt: No such file or directory
[2025-09-15T22:34:17.413+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-15T22:34:17.446+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-15T22:34:17.454+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=just_orchestration, task_id=prepare_workspace, execution_date=20250915T180404, start_date=20250915T223416, end_date=20250915T223417
[2025-09-15T22:34:18.007+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task prepare_workspace (Bash command failed. The command returned a non-zero exit code 1.; 419)
[2025-09-15T22:34:18.040+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-15T22:34:18.179+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
