[2025-09-15T22:57:45.818+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.prepare_workspace manual__2025-09-15T22:52:20.139806+00:00 [queued]>
[2025-09-15T22:57:46.140+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.prepare_workspace manual__2025-09-15T22:52:20.139806+00:00 [queued]>
[2025-09-15T22:57:46.156+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-15T22:57:46.961+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): prepare_workspace> on 2025-09-15 22:52:20.139806+00:00
[2025-09-15T22:57:47.146+0000] {standard_task_runner.py:60} INFO - Started process 410 to run task
[2025-09-15T22:57:47.515+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'prepare_workspace', 'manual__2025-09-15T22:52:20.139806+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpfsk8jkci']
[2025-09-15T22:57:47.639+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask prepare_workspace
[2025-09-15T22:57:49.842+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.prepare_workspace manual__2025-09-15T22:52:20.139806+00:00 [running]> on host f5911201595b
[2025-09-15T22:57:51.686+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='prepare_workspace' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T22:52:20.139806+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-15T22:52:20.139806+00:00'
[2025-09-15T22:57:51.691+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T22:57:51.696+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    mkdir -p /shared_data/Models\n    mkdir -p /shared_data/data\n    mkdir -p /shared_data/metrics\n    echo "Pipeline started at $(date)" > /shared_data/Models/pipeline_log.txt\n    ']
[2025-09-15T22:57:51.721+0000] {subprocess.py:86} INFO - Output:
[2025-09-15T22:57:51.732+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/shared_data’: Permission denied
[2025-09-15T22:57:51.739+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/shared_data’: Permission denied
[2025-09-15T22:57:51.747+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/shared_data’: Permission denied
[2025-09-15T22:57:51.755+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 5: /shared_data/Models/pipeline_log.txt: No such file or directory
[2025-09-15T22:57:51.756+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-15T22:57:51.799+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-15T22:57:51.808+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_orchestration, task_id=prepare_workspace, execution_date=20250915T225220, start_date=20250915T225745, end_date=20250915T225751
[2025-09-15T22:57:52.158+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task prepare_workspace (Bash command failed. The command returned a non-zero exit code 1.; 410)
[2025-09-15T22:57:52.211+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-15T22:57:52.360+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
