[2025-09-15T22:56:55.351+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: just_orchestration.prepare_workspace manual__2025-09-15T22:51:46.957955+00:00 [queued]>
[2025-09-15T22:56:55.372+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: just_orchestration.prepare_workspace manual__2025-09-15T22:51:46.957955+00:00 [queued]>
[2025-09-15T22:56:55.373+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-15T22:56:55.424+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): prepare_workspace> on 2025-09-15 22:51:46.957955+00:00
[2025-09-15T22:56:55.434+0000] {standard_task_runner.py:60} INFO - Started process 388 to run task
[2025-09-15T22:56:55.446+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'just_orchestration', 'prepare_workspace', 'manual__2025-09-15T22:51:46.957955+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/another.py', '--cfg-path', '/tmp/tmprm2vn_xn']
[2025-09-15T22:56:55.452+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask prepare_workspace
[2025-09-15T22:56:55.643+0000] {task_command.py:423} INFO - Running <TaskInstance: just_orchestration.prepare_workspace manual__2025-09-15T22:51:46.957955+00:00 [running]> on host f5911201595b
[2025-09-15T22:56:55.927+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='williams' AIRFLOW_CTX_DAG_ID='just_orchestration' AIRFLOW_CTX_TASK_ID='prepare_workspace' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T22:51:46.957955+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-15T22:51:46.957955+00:00'
[2025-09-15T22:56:55.931+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-15T22:56:55.935+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    mkdir -p /opt/Models\n    mkdir -p /opt/data\n    mkdir -p /opt/metrics\n    echo "Pipeline started at $(date)" > /opt/Models/pipeline_log.txt\n    ']
[2025-09-15T22:56:55.955+0000] {subprocess.py:86} INFO - Output:
[2025-09-15T22:56:55.965+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/Models’: Permission denied
[2025-09-15T22:56:55.972+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/data’: Permission denied
[2025-09-15T22:56:55.979+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/metrics’: Permission denied
[2025-09-15T22:56:55.991+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 5: /opt/Models/pipeline_log.txt: No such file or directory
[2025-09-15T22:56:55.993+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-15T22:56:56.040+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-15T22:56:56.049+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=just_orchestration, task_id=prepare_workspace, execution_date=20250915T225146, start_date=20250915T225655, end_date=20250915T225656
[2025-09-15T22:56:56.203+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task prepare_workspace (Bash command failed. The command returned a non-zero exit code 1.; 388)
[2025-09-15T22:56:56.245+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-15T22:56:56.328+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
